services:
  api:
    build: .
    container_name: shopify_api
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MONGO_URI=${MONGO_URI}
      - CACHE_TTL=${CACHE_TTL}
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:7-alpine
    container_name: shopify_redis
    ports:
      - "6380:6379"

  mongo:
    image: mongo:7
    container_name: shopify_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
